### ISSUE TITLE
Relationship between src/custom/ and src/servables/custom?

### ISSUE THREAD

**Issue by erickim555** [NVIDIA/tensorrt-inference-server#170]
Hello, I need to implement a custom backend to support Caffe2 object detection Detectron models. I see there are two src directories relating to "custom" things: src/custom and src/servables/custom/.

What is the relationship between these two? If I wanted to implement a custom backend to support my usecase (detailed below), where should I make my changes? Thank you!

Context: Detectron models have a batch inference output format that is not supported by the default caffe2 backend, namely:
```
Input:
  image_data: shape=[nb_images, nb_channels, img_height, img_width]
Outputs:
  boxes: shape=[nb_boxes, ]. (x1, y1, x2, y2, float confidence, int category_index)
    boxes are organized sequentially by batch.
  batch_splits: shape=[nb_images]. records how many boxes belong to each image. used to split "boxes" into image-specific boxes.
```

whereas the default caffe2 backend expects the following:
```
Input:
  image_data: shape=[nb_images, nb_channels, img_height, img_width]
Outputs:
  boxes: shape=[nb_images, nb_boxes, 6]
```
Running a Detectron model through TRTIS with the default caffe2 backend always fails, due to various output size checks that are violated.

My custom backend will be very similar to the default caffe2 backend, but with custom handling of the batched output that handles "boxes", "batch_splits" to emit image-specific boxes.
