### ISSUE TITLE
Unable to run TensorRTIS on AKS

### ISSUE THREAD

**Issue by rakelkar** [NVIDIA/tensorrt-inference-server#378]
I am trying to run TensortRTIS on AKS but get the following failure:
```
$ kubectl logs trt
trtserver: error while loading shared libraries: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
```

I tried installing NVIDIA drivers, but it didnt help... (just running the simple-string example for CPU only... not running GPU)
https://docs.microsoft.com/en-us/azure/aks/gpu-cluster

My podspec is:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: trt
  namespace: default
spec:
  containers:
  - args:
    - --model-store=gs://rakelkar1/trt_sample
    - --allow-poll-model-repository=false
    - --allow-grpc=true
    - --allow-http=true
    - --grpc-port=9000
    - --rest-port=8080
    command:
    - trtserver
    env:
    - name: PORT
      value: "8080"
    image: nvcr.io/nvidia/tensorrtserver:19.05-py3
    imagePullPolicy: IfNotPresent
    name: user-container
    ports:
    - containerPort: 8080
      name: user-port
      protocol: TCP
```
